### ISSUE TITLE
Instance 3 error

### ISSUE THREAD

**Issue by Cameron1470** [sentry07/crestron-multiple-xpanel#1]
Getting an issue with specifically the 3rd instance. All other open up the XPanel app and work as should. Running any .c3p file using Instance 3 gives the error:

> Adobe AIR
> Application descriptor could not be found for this application. Try re-installing or contacting the publisher for assistance

Have tried uninstalling and reinstalling this CMD file but still getting the same issue.

**Comment by Cameron1470** [comment]
Had a little rummage around and there was a "application.xml" missing from C:\Crestron XPanels\CrestronXPanel-3\META-INF\AIR

Copied it across from one of the other XPanel folders and it fixed it! Not sure what the reason is for it being repeatedly missed during the install? Looks alright in the .cmd file

**Comment by Cameron1470** [comment]
On further inspection, after copying the application.xml from the Instance 2 folder into the Instance 3 folder the 2nd and 3rd instance are now the same. You can of course open the .xml of the third xPanel folder and manually change the id which has fixed it

**Comment by sentry07** [comment]
Yeah, I'm not sure what would be causing that issue. The code is exactly the same for creating each instance and I see the application.xml in my instance 3 folder. I just ran the uninstaller and then the installer again and all 5 instances are separate and working. One of the shortcomings of using CMD files is there's no search and replace so I'm creating a PowerShell script to do that for me. I'm wondering if that's failing to run for some reason. Though, it's weird that it's failing on the same one every time.

**Comment by Cameron1470** [comment]
I've tried it on another machine and it worked fine, very strange! But yeah it seems to be a machine specific blip. Thanks for the code though, nice and handy

**Comment by sentry07** [comment]
Unless this is reproducible, I'm going to go ahead and close this issue.

**Comment by luk-marshal** [comment]
I had exactly the same problem.
Steps:
1. I downloaded the ZIP file
2. I unpacked the archive
3. I installed it with administrator privileges.

Then only the third xpanel didn't work, but the others worked properly.
Finally fixed it with @Cameron1470's instructions (I copied the application.xml file)
